"user strict";
ffmpeg = require("fluent-ffmpeg"),
ytdl = require("ytdl-core"), // youtube video downloader
//progress = require("progress-stream"), // will use later for progress bar and progress percentages 

// main class
function MP3DOWNLOADER(options) {

    this.youtubeBaseUrl = "http://www.youtube.com/watch?v=";

    this.fileSavePath = options.fileSavePath;

    // set ffmegpath after initialized in express - save the binary on the server
    if (options.ffmpegPath) {
        ffmpeg.setFfmpegPath(options.ffmpegPath);
    }     
};

// the main method - main parameter is a string passed in from the front end, called the videoID
MP3DOWNLOADER.prototype.download = function(videoID){
    
    // make the full URL of the video being downloaded
    var youtubeFullUrl = this.youtubeBaseUrl + videoID;

        ytdl.getInfo(youtubeFullUrl, function(error, info){

            // if it fails to get info about the video - for example user enters wrong link
            if (error) {
                callback(error.message);
            } else {
                
            // download the video with ytdl using the provided info
            var downloadVideoStream = ytdl.downloadFromInfo(info);
                
            // this is where the encoding takes place if I get a response - a string generated by ytdl
            downloadVideoStream.on("response", function(){
                    
                // initiate the main object that will be returned by the API as jsonp
                var videoInfo = {
                    // fileName
                    // songName
                    // artist
                    // songThumbnail
                    // fileSavePath
                } 
                
                // initialize the encoder, source being the downloaded video 
                var encoderJob = new ffmpeg({
                    source: downloadVideoStream
                });
                    
                // encoder at work - set the audiocodec and .mp3 format 
                encoderJob.withAudioCodec('libmp3lame');
                encoderJob.toFormat('mp3');
                
                // tracking if an error occurs - maybe video wasnt downloaded, or issues with ffmpeg
                downloadVideoStream.on("error", function(error){
                    callback(error.message);
                });
                
                // in the API(express) this is represented as "finished", which is the next step from this
                downloadVideoStream.on("end", function() {
                    // name of the file saved on your PC
                    // var downloadFileName = use youtube API to get the video title and them .trim() it + "mp3"
                    // videoInfo.fileName = downloadFileName;
                    
                    // videoInfo.songName = need from youtube API

                    // videoInfo.artist = need from youtube API

                    videoID.songThumbnail = "https://img.youtube.com/vi/" + videoID + "/default.jpg"
                    callback(videoInfo);
                });
                
                // this is where the actual save is performed
                // downloadVideoStream.saveToFile(this.fileSavePath);
            });
        }       
    });
}
   

module.exports = sindatybt2mp3;

